# Generated by Django 5.0.6 on 2024-06-14 22:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0001_initial'),
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='armor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='armor', to='shop.weapon'),
        ),
        migrations.AddField(
            model_name='player',
            name='hands',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hands', to='shop.weapon'),
        ),
        migrations.AddField(
            model_name='player',
            name='head',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='head', to='shop.weapon'),
        ),
        migrations.AddField(
            model_name='player',
            name='legs',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legs', to='shop.weapon'),
        ),
    ]
