# Generated by Django 5.0.6 on 2024-06-18 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0002_player_armor_player_hands_player_head_player_legs'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enemy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('hp', models.IntegerField(default=5)),
                ('money_drop', models.IntegerField(default=0)),
                ('attack', models.IntegerField()),
                ('defense', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
